### ISSUE TITLE
Incorrect Display perspective

### ISSUE THREAD

**Issue by gkerdal** [jajuk-team/jajuk#2008] opened 2016-12-11 18:37 UTC
I run Jajuk 1.10.9 on Ubuntu 16.10, the Display perspective doesn't show the inner views.

![jajuk-display-perspective](https://cloud.githubusercontent.com/assets/9927252/21082150/bfe006f4-bfd5-11e6-9ae2-24926f6e15ac.png)

The console trace :
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/jgoodies/common/base/Preconditions
	at com.jgoodies.animation.renderer.AbstractTextRenderer.setText(AbstractTextRenderer.java:135)
	at com.jgoodies.animation.swing.components.BasicTextLabel.setText(BasicTextLabel.java:212)
	at org.jajuk.ui.views.AnimationView$2.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.jgoodies.common.base.Preconditions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more

**Comment by bflorat** [comment] 2016-12-11 19:39
Thanks Gwen. I think that it is a Debian bug  :  
- our 1.10.9 official distribution comes with animation 1.4.2 and I cannot reproduce this bug with this version
- the debian jessie package (probably used in ubuntu 16.10) contains animation 1.2.0-5 [1]. I think that this animation version is missing a dependency (libjgoodies-common-java). Our distribution comes with jgoodies-common-1.6.0.
- Note that Stretch comes with animation 1.4.3.

My best guess would be to report a bug to Debian [3] so they they add the missing dependency in Jessie or as you suggested to find another lib (or to write our own code)...

[1] https://packages.debian.org/jessie/libjgoodies-animation-java
[2] https://packages.debian.org/stretch/libjgoodies-animation-java
[3]  https://www.debian.org/Bugs/Reporting

**Comment by gkerdal** [comment] 2016-12-11 23:20
It seems that ubuntu 16.10 is closer to stretch according to the file /etc/debian_version on my system. FYI, /usr/share/java contains the following version : 
animation-1.4.3
jgoodies-common-1.7.0

Thanks for the links, I'll have a look very soon.

**Comment by gkerdal** [comment] 2016-12-14 20:36
jgoodies-common is not present in the classpath inside the file jajuk.jar, in [1] the dependance is effectively mentionned. I'll try to declare the missing dependency.

[1] https://packages.debian.org/stretch/jajuk

**Comment by bflorat** [comment] 2017-02-26 20:16
Thanks Gwen. Can I assume this bug is now handled by Debian (and then Ubuntu which is based upon Debian packages) and that we can close this ticket ?

**Comment by gkerdal** [comment] 2017-03-02 21:32
Hi Bertrand,
Felix fixed it but it's not yet available. I reinstalled Jajuk today on my
PC, it's still the old version. See below Felix Natter's response
(2017-02-03) :

"I fixed this:

https://anonscm.debian.org/git/pkg-java/jajuk.git/commit/?id=580e7cd22a1
5d51df070d32bec4a4cc99ad2a401

I will publish this to Debian unstable as soon as the stretch freeze is
over.

Unfortunately, this problem existed for quite a while, so we would have to
do _several_
SRUs to fix it in various Ubuntu releases (and in Debian stretch).
But it's doable because the fix is very simple, so if anyone wants to drive
this,
please go ahead!

Cheers and Best Regards,
Felix"



2017-02-26 21:16 GMT+01:00 Bertrand Florat <notifications@github.com>:

**Comment by bflorat** [comment] 2017-03-03 20:00
Hi Gwen,
Yes but we can't anything more on it, it's now a Debian/Ubuntu bug, isn't it ?

**Comment by gkerdal** [comment] 2017-03-08 19:52
Hi Bertrand,
you're right, we can close it.

Last point : the download link from jajuk.info points
to jajuk_1.10.9-2_all.deb which has the same problem. Is it possible to
publish a corrected .deb file ?

jgoodies-common is not mentionned in the MANIFEST.MF file.
This way, anyone can install it from this location to solve the problem.

Cheers,

Gwen.

2017-03-03 21:00 GMT+01:00 Bertrand Florat <notifications@github.com>:

**Comment by bflorat** [comment] 2017-03-11 09:18
Hi Gwen, are you sure our deb distro has the same problem ? I'm using it everyday under my xubuntu and the display view is fine...
And indeed, our politic has always been to say that our own packages are certified by us and should work.

**Comment by gkerdal** [comment] 2017-03-11 12:38
Hi Bertrand,

I checked the content of the jajuk_1.10.9-2_all.deb (downloaded from
sourceforge):
It doesn't contain jgoodies-common-*.jar file and the MANIFEST.MF file
doesn't refer to it, so on your Xubuntu, the dependency is well resolved
between jgoodies-animation and jgoodies-common. Your guess of a debian bug
sounds perfectly right.

If we produce a new jajuk_1.10.9-3_all.deb file explicitly refering to
jgoodies-common-*.jar, that could solve the problem on some debian
distribution. What do you think of this workaround ?

Cheers,

Gwen.


2017-03-11 10:18 GMT+01:00 Bertrand Florat <notifications@github.com>:

**Comment by bflorat** [comment] 2017-03-11 14:02
Gwen, 
Well, I had a look at at it  and if I understand well : 
- Actually, you're right, my jajuk 1.10.9-2 debian (using our official package) contains no jgoodies-common but an old animation version (1.2.0) but it doesn't need it and it works.

- You can see at [1] that animation 1.2.0 has no need for jgoodies-common as 1.4.1 does [2]

- In our develop branch (1.11.0), the packaging should be ok as it comes with animation 1.4.3 and jgoodies-common, you can check it at [3].

So our official package is OK apart from the fact that it used deprecated animation lib, isn't it ?

BTW, we should release soon jajuk 1.11.0 with this lib upgrade and finish all libs upgrades (remove cobra...). I hope we can work on it this year (I'll have more time in mid-april, I'm currently overbooked)

What do your think ?

[1] https://repo1.maven.org/maven2/com/jgoodies/animation/1.2.0/animation-1.2.0.pom
[2] https://repo1.maven.org/maven2/com/jgoodies/animation/1.4.1/animation-1.4.1.pom
[3] http://integration.jajuk.info:8080/job/unstable/

**Comment by gkerdal** [comment] 2017-03-12 18:02
Hi Bertrand,

yes the official package is ok.
I'll have a look at the develop branch to see if it's ok.

I would be glad to help you on next version. I can have a look for cobra
replacement, CSSBox [1] seems to be a potential candidate.

Cheers,

Gwen.

[1] http://cssbox.sourceforge.net/about.php

2017-03-11 15:02 GMT+01:00 Bertrand Florat <notifications@github.com>:

**Comment by bflorat** [comment] 2017-03-13 13:56
Hi Gwen,

Glad to hear you can work on the wikipedia view cobra lib replacement. I didn't check the lib you mentioned yet but before using another java lib, I'd like to be sure we can't use the JRE 7+ classes, as described in [1] ? so we no more depend upon one or more libs. 

I see two objectives in the refactoring : 
1) upgrade dependencies
2) drop as many dependencies as possible

What do you think ?

[1] https://docs.oracle.com/javase/8/javafx/interoperability-tutorial/swing-fx-interoperability.htm

**Comment by gkerdal** [comment] 2017-03-15 22:40
Hi Bertrand,

the 1.11 version (develop branch) works fine on my system.

Good idea to have look at JavaFX instead of adding a new library. I'll try
to integrate the JavaFx Browser for wikipedia in my local Jajuk. I only
start a JavaFX tutorial today, not an expert.

JavaFX is integrated in Java 8, but not sure it's available on all JVM so I
hope the packaging work is not too tricky. It could lead to less supported
platforms, anyway JavaFX is the future in Java not Swing.

Cheers,

Gwen.

2017-03-13 14:56 GMT+01:00 Bertrand Florat <notifications@github.com>:

**Comment by bflorat** [comment] 2017-03-16 20:09
OK, Thanks Gwen to look at this. I hope you will not spend to much time on JavaFX on this case, it's just a wrapper if I understand well. I'm not pretty sure JavaFX is the future of GUI, but maybe...
Can you confirm this work on Java 7 ? If not, I'm not comfortable with forcing the version upgrade.

Last thing :  if everything's ok, we'll have to test it under all OS (OSX, Windows and Linux), I have some virtual machines if required.

Cheers

**Comment by bflorat** [comment] 2019-11-09 07:32
Works with linux tarrball

**Closed by bflorat** 2019-11-09 07:32 UTC
Labels: C: User Interface, T: Bug
