### ISSUE TITLE
Jajuk won't read flac files under Windows

### ISSUE THREAD

**Issue by Rhair3** [jajuk-team/jajuk#2061] opened 2020-07-22 03:46 UTC
I loaded jajuk on my windows 10 laptop and it will not play flac files.  It won't read them in the designated folder when it scans to folder for music and it won't play if I try to drag and drop the files in the program.

**Comment by centic9** [comment] 2020-10-18 07:12
Please set loglevel to DEBUG under Configuration -> Advanced and provide the Jajuk logfile from a full device re-scan.

**Comment by caribouu** [comment] 2021-07-22 08:09
I am having a similar issue. Windows 8.1, latest Jajuk version. Any album that has a flac file doesn't show the files, only the album folder/name. I have a logfile from a full device re-scan. Where do I send it?

**Comment by bflorat** [comment] 2021-07-24 17:24
Thanks for reporting. I can reproduce this under W10. Looks like Jajuk doesn't use mplayer.exe but its internal Java-based player for mp3, ogg and some others formats but doesn't support flac as this format is handled only by embedded mplayer.exe. Probably a packaging issue. We have to investigate.  No need for logs for now, thanks.

**Comment by bflorat** [comment] 2021-07-31 18:55
Fixed in upcoming Jajuk 12

**Closed by bflorat** 2021-07-31 18:55 UTC
Labels: C: Functional, R: Fixed, T: Bug
